import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getDictionary } from "./dictionaries";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resume-Site",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: {locale:string}
}>) {
  const {locale} =await params;
  const dir = locale === 'fa'? 'rtl': 'ltr'

 const dict = await getDictionary(locale as 'fa' | 'en');
 const navbarLabels = dict.navbar

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
          <Toaster position="top-right" />
        <Navbar labels={navbarLabels}/>
        {children}
      </body>
    </html>
  );
}
